export const propMap = {
  "% to Bullet Jump": "v",
  "% Aim Glide and Wall Latch": "at",
  "% Sprint Speed": "f",
  "% Slide": "l",
  "% Shield Recharge": "r",
  "% Shield Capacity": "s",
  " <DT_ELECTRICITY>Electricity": "7",
  "% Energy Max": "e",
  "% Counter Chance": "cc",
  " Loot Radar": "lr",
  "% Chance to Resist Knockdown": "k",
  "% Faster Knockdown Recovery": "y",
  "% Health": "h",
  "% Damage during Bleedout": "ddb",
  " Enemy Radar": "er",
  "% <DT_POISON>Toxin Resistance": "pr",
  "% <DT_RADIATION>Radiation Resistance": "rr",
  "% Damage Resistance on Knockdown": "drk",
  "% <DT_FREEZE>Cold Resistance": "cr",
  "% <DT_FIRE>Heat Resistance": "fr",
  "% <DT_ELECTRICITY>Electricity Resistance": "ir",
  "% chance to unlock locked lockers.": "ll",
  "% Casting Speed": "c",
  "% Bleedout Reduction": "br",
  "% Auto Parry Chance": "apc",
  "% Armor": "a",
  "% Ability Strength": "t",
  "% Ability Range": "g",
  "% Ability Efficiency": "x",
  "% Ability Duration": "u",
  "% Faster Stagger Recovery": "sr",
  "% Holster Speed": "hr",
  "% Dead Aim": "da",
  " 'Purity'": "vp",
  " Magazine Capacity": "bL",
  " 'Truth'": "vt",
  " Base Status Chance": "i2",
  " 'Entropy'": "ve",
  " Range": "ar",
  " 'Sequence'": "vs",
  "% Status Chance": "2",
  " 'Justice'": "vj",
  "% Melee Damage": "K",
  "% <DT_POISON>Toxin": "6",
  " 'Blight'": "vb",
  "% Weapon Range for 4s on Status Effect.": "rse",
  "% Projectile Flight Speed": "V",
  "% Multishot": "S",
  "% Critical Chance": "0",
  "% Life Steal": "ls",
  "% Magazine Capacity": "L",
  "% Fire Rate": "R",
  "% Chance to Explode (Use with Caution)": "exp",
  "% Status Duration": "3",
  "% <DT_SLASH>Slash": "A",
  "% Damage to Infested": "I",
  "% Damage to Grineer": "G",
  "% Damage to Corrupted": "od",
  "% Damage to Corpus": "C",
  "% Reload Speed": "F",
  " Punch Through": "P",
  "% <DT_IMPACT>Impact": "8",
  "% <DT_FREEZE>Cold": "5",
  "% <DT_FIRE>Heat": "4",
  "% <DT_PUNCTURE>Puncture": "9",
  "% <DT_ELECTRICITY>Electricity": "7",
  "% Damage": "D",
  "% Critical Damage": "1",
  "% Ammo Maximum": "M",
  "% Spread": "spr",
  "% Fire Rate (x2 for Bows)": "R",
  "% <DT_SENTIENT>Tau Resistance": "tr",
  "% Bonus Damage on final shot. Requires Magazine 6 or higher.": "lsb",
  "% Damage to Sentients": "smd",
  "% Extra Damage against a Marked Enemy": "edm",
  "% chance to apply <DT_SLASH> on Critical": "ac",
  "% Attack Speed": "J",
  "s Combo Duration": "N",
  "% Finisher Damage": "X",
  "% Zoom": "H",
  "% Weapon Recoil": "Z",
  "% Blast Radius": "brad",
  "% Damage on first shot in Magazine": "fsb",
  "% to Headshot Multiplier": "hm",
  "s Combo Duration when Aiming": "N",
  "% Accuracy": "acc",
  " Extra Damage on Melee Attacks, or Lethal Damage on Finishers.": "ld",
  "% Melee Slam Damage": "msd",
  "% Range": "T",
  "% Channeling Damage": "B",
  "% chance to increase Melee Combo Counter when <DT_SLASH>Slash Status deals damage.": "ccws",
  "% Channeling Efficiency": "U",
  " Bounce": "bnc",
  "% Melee Damage per Status Type affecting the target.": "co",
  "% Attack Speed (Max: 75%) for 4s on Critical Hit": "bsk",
  "% Critical Hit Chance for Slide Attack": "E",
  "% Status Chance per Combo Multiplier": "sccm",
  "% Critical Chance stacks with Combo Multiplier": "bldr",
  "% Status Duration on Hit": "3",
  "% Ammo Pickup": "ap",
  " Energy Rate": "es",
  "% Flight Speed": "fl",
  "% Status Chance when Aiming": "2",
  "% DAMAGE": "D",
  " PUNCH THROUGH": "P",
  "% Critical Chance and Damage when Aiming": "cd",
  "% Charge Rate": "ca",
  "% Chance to Resist Staggers/Knockdowns when Aiming": "ck",
  "% Aim Glide/Latch Time": "at",
  "% Parkour Velocity": "at",
  "% Aura Strength": "as",
  "% Aura Effectiveness": "ae",
  "% Evasion": "ev",
  "% Friction": "i",
  "% Critical Chance when Aiming for 1.5s": "0",
  "% Critical Damage when Aiming for 1.5s": "1",
  "% Accuracy when Aiming for 1.5s": "acc",
  "% Fire Rate when Aiming for 1.5s": "R",
  "% Status Chance when Aiming for 1.5s": "2",
  "% Movement Speed when Aiming": "m",
  "% Status Duration on Self": "sds",
  "% Magazine Reloaded/s when Holstered": "lal",
  "% Movement Speed for 2.5s": "ckm",
  "% Ability Strength of Squadmates": "tt",
  "% Shield Resistance to Ice Levels": "wc",
  " Energy": "her",
  "% Total Damage": "oad",
  "% Self-damage": "sb",
  "% Fire/Charge Rate": "rc",
  "% Reload Speed for 1.5s": "F",
  "% Damage for 1.5s": "D",
  "% Spread when Aiming": "spr",
  "% Damage for 3s": "dmg",
  " Heal Rate/s": "hps",
  "% Hit Chance": "eac",
  "% Speed": "esp"
};

export const extPropMap = {
  "On Headshot:": "onHeadshot",
  "On Headshot Kill:": "onHeadshotKill",
  "On Kill:": "onKill",
  "On Reload:": "onReload",
  "On Hit:": "onHit",
  "On Ability Cast:": "onAbilityCast",
  "On Melee Channel Kill:": "onMeleeChannelKill",
  "On Reload From Empty:": "onReloadFromEmpty",
  "On Dodge:": "onDodge",
  "On Equip:": "onEquip",
  "Fatal strikes against an enemy also perform a Codex Scan. Scans require an equipped Codex Scanner and an available charge.": "scan"
};

export const extRexProp = {
  "Grenades have 17% chance to stick to surfaces.": ["stick", 17],
  "Reduces the chance an enemy will hear gunfire by 25%.": ["slc", 25],
  "Enemies killed explode, dealing 100 Damage shortly after death.": ["kb", 100],
  "Shots now bounce up to 1x and travel 5% further.": ["but", 1],
  "Grenades tether up to 2 enemies from 4m away.": ["el", 2],
  "Increase damage by +40%": ["!oad", 40],
  "if the target is over 45m away.": ["ify", 15],
  "Increases Magazine Capacity by +50%.": ["L", 50],
  "Blocking taunts enemies within 6 meters to target you instead of allies.": ["!gdr", 15],
  "Restores 1 Health per Status Type affecting the target.": ["hlr", 1],
  "Converts 50% of Energy used to up to 50 Bonus Damage on next Melee Attack.": ["exd", 50],
  "Applying Status Effects with weapons increase Ability Strength by 4% for 1s.": ["t", 25.5],
  "Convert +7.5% of Damage on Health to Energy": ["rg", 7.5],
  "Convert +10% of Damage on Health to Energy": ["rg", 10],
  "Drains Energy to stop Lethal Damage with 10% Efficiency.": ["z", 10],
  "Drains Energy to stop Lethal Damage with 40% Efficiency.": ["z", 40],
  "Health Orbs grant 75 Armor, stacking up to 3x. Taking damage will consume a stack after 3s.": ["hc", 50],
  "Energy orbs grant 9% more Ability Strength to your next cast.": ["ec", 50 / 6],
  "Health pickups give +10% Energy. Energy pickups give +10% Health.": ["eq", 10],
  "Reduces damage by 2% when Airborne.": ["adr", 2],
  "Reduces damage by 10% when Airborne.": ["adr", 10],
  "<DT_IMPACT>Impact damage reduces enemy armor by 1.": ["si", 1],
  "16% Damage taken is reflected when Blocking attacks while Channeling.": ["ref", 16],
  "Converts unused Ammo Pickups into Primary Weapon Ammo. Pistol <AMMO_MUTATION> 1 and Shotgun/Sniper <AMMO_MUTATION> 2.": ["am", 30]
};
